"""add_user_settings_fields

Revision ID: 0aa8e7b50a6d
Revises: 6a60ec907861
Create Date: 2025-10-03 23:13:26.747810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa8e7b50a6d'
down_revision: Union[str, None] = '6a60ec907861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('institution', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('dark_mode', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('interface_scale', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('default_analysis_model', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('push_notifications', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('analysis_notifications', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('report_notifications', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('data_retention_period', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('anonymous_analytics', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('data_sharing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'data_sharing')
    op.drop_column('users', 'anonymous_analytics')
    op.drop_column('users', 'data_retention_period')
    op.drop_column('users', 'report_notifications')
    op.drop_column('users', 'analysis_notifications')
    op.drop_column('users', 'push_notifications')
    op.drop_column('users', 'email_notifications')
    op.drop_column('users', 'default_analysis_model')
    op.drop_column('users', 'interface_scale')
    op.drop_column('users', 'dark_mode')
    op.drop_column('users', 'institution')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###