"""normalize_usernames_and_emails_to_lowercase

Revision ID: 5a289521e8b4
Revises: 6d635b20f553
Create Date: 2025-10-04 00:15:10.045096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a289521e8b4'
down_revision: Union[str, None] = '6d635b20f553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Normalize existing usernames and emails to lowercase
    op.execute("UPDATE users SET username = LOWER(username) WHERE username IS NOT NULL")
    op.execute("UPDATE users SET email = LOWER(email) WHERE email IS NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: We cannot reliably reverse lowercase normalization
    # as we don't know the original case
    pass
    # ### end Alembic commands ###