"""add_gdpr_and_marketing_consent_fields

Revision ID: 6a60ec907861
Revises: 933542155b0f
Create Date: 2025-10-03 22:04:38.632967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a60ec907861'
down_revision: Union[str, None] = '933542155b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gdpr_consent', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('gdpr_consent_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('marketing_consent', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('marketing_consent_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'marketing_consent_date')
    op.drop_column('users', 'marketing_consent')
    op.drop_column('users', 'gdpr_consent_date')
    op.drop_column('users', 'gdpr_consent')
    # ### end Alembic commands ###