"""Add breast cancer analysis support

Revision ID: 933542155b0f
Revises: 97b7ab3d44cf
Create Date: 2025-09-27 14:09:50.289712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '933542155b0f'
down_revision: Union[str, None] = '97b7ab3d44cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnosis_results', sa.Column('analysis_type', sa.String(), nullable=True))
    op.add_column('diagnosis_results', sa.Column('additional_results', sa.JSON(), nullable=True))
    op.alter_column('diagnosis_results', 'diagnosis_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diagnosis_results', 'diagnosis_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('diagnosis_results', 'additional_results')
    op.drop_column('diagnosis_results', 'analysis_type')
    # ### end Alembic commands ###